# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  test-py39:
    docker:
      - image: cimg/python:3.9

    working_directory: ~/repo

    steps:
      - checkout
      - run:
          name: Save Python Version
          command: |
            python --version > pythonversion

      - run:
          name: install dependencies
          command: |
            python3 -m venv ~/venv
            . ~/venv/bin/activate
            pip install -r requirements.txt
            pip install -r requirements.local.txt
            mkdir -p test-reports

      - run:
          name: run tests
          command: |
            . ~/venv/bin/activate
            pytest --verbose --junit-xml=test-reports/pytest.xml

      - store_artifacts:
          path: test-reports
          destination: test-reports-py39

      - store_test_results:
          path: test-reports
  publish:
    docker:
      - image: cimg/python:3.9

    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: install dependencies
          command: |
            python3 -m venv ~/venv
            . ~/venv/bin/activate
            pip install twine
      - run:
          name: Publish to PyPI
          command: |
            . ~/venv/bin/activate
            python setup.py sdist
            twine upload --username $PYPI_USERNAME --password $PYPI_PASSWORD dist/*

workflows:
  version: 2
  test-and-publish:
    jobs:
      - test-py39:
          filters:
            tags:
              only: /.*/
      - publish:
          requires:
            - test-py39
          filters:
            tags:
              only: /^v[0-9]+(\.[0-9]+)*.*/
            branches:
              ignore: /.*/
          context: ustudio-tornado-cors-publisher
